### PR TITLE
Prepend original client address to SOCKS4 login

### PR DESCRIPTION
**Pull request by wertarbyte**
it is often useful to forward connections from a router to a proxy on a different machine; this change enables the proxy server to utilize the original requesting host.

### CODE REVIEW

**Comment by darkk** [comment]
- allocating memory for user_str if the feature is not used is not nice.
- as far as I see, `user_str` is never deallocated, so memory leaks 
- you should pass sizeof(client->clientaddr), not sizeof(struct sockaddr) to getnameinfo.
- why prepending instead of appending? :) Whas socks server implements this logic?
- why only socks4? `login_send_origin` is not validated, so configuration with http-connect and login_send_origin is accepted but does nothing.
- why use socks4 instead of PROXY protocol? it feels more natural for the task.

**Comment by wertarbyte** [comment]
Hello,
I refactored the code and got rid of the user_str variable; I also fixed the sizeof line.
Regarding the questions why I use SOCKS4: I am using redsocks to redirect connections to a custom proxy script (Perl), and just using the simple protocol seemed to be the easy choice. That's also the reason why I prepend the ip address; that way I can just use anything up to the first ';', since the format of the address is well defined and cannot contain that character - so in the end, it is pure convenience.

**Comment by darkk** [comment]
`X-Forwarded-For` is not the only one format to transmit client src IP to the proxy, I've added `Forwarded` at 4521797847eeaaef035a94d58e03f1a8111dc96f, it may be useful for you.

**Comment by wertarbyte** [comment]
I merged your changes into my branch and modified my SOCKS4 code to use your config enum. Please consider merging it.

I don't remember where I've seen X-Forwarded-For, it was probably some time ago.

**Comment by wertarbyte** [comment]
(I merged the changes into a more compact patch)

**Pull request closed without merging**
