### PR TITLE
Compilation on Android

### PR DESCRIPTION
**Pull request by madeye**
Thanks to redsocks, we have built several proxy related apps for Android users. 

Here are patches and makefiles for Android NDK build system, including a porting of libevent-1.4.3 from the official AOSP.

It seems not suitable to include libevent's source codes in redsocks. Maybe a patch should be provided instead.

### CODE REVIEW

**Comment by SunPj** [comment]
I've caught following error
```
[kraken@dhcppc2 android]$ ndk-build
[x86] Compile        : redsocks <= parser.c
[x86] Compile        : redsocks <= main.c
[x86] Compile        : redsocks <= redsocks.c
[x86] Compile        : redsocks <= log.c
[x86] Compile        : redsocks <= http-connect.c
[x86] Compile        : redsocks <= socks4.c
[x86] Compile        : redsocks <= socks5.c
[x86] Compile        : redsocks <= http-relay.c
[x86] Compile        : redsocks <= base.c
[x86] Compile        : redsocks <= base64.c
[x86] Compile        : redsocks <= md5.c
[x86] Compile        : redsocks <= http-auth.c
[x86] Compile        : redsocks <= utils.c
[x86] Compile        : redsocks <= redudp.c
[x86] Compile        : redsocks <= dnstc.c
[x86] Compile        : redsocks <= version.c
[x86] Compile        : event <= evbuffer.c
jni/libevent/evbuffer.c:31:20: fatal error: config.h: No such file or directory
 #include "config.h"
                    ^
compilation terminated.
make: *** [obj/local/x86/objs/event/libevent/evbuffer.o] Error 1
```

**Comment by yanggis** [comment]
Hi I also got the same error when compiling for Android using NDK, any tips? thanks.
E:\Android_SDK\android-ndk-r10e\redsocks-0.4\android>ndk-build
[armeabi] Compile thumb  : redsocks <= parser.c
[armeabi] Compile thumb  : redsocks <= main.c
[armeabi] Compile thumb  : redsocks <= redsocks.c
[armeabi] Compile thumb  : redsocks <= log.c
[armeabi] Compile thumb  : redsocks <= http-connect.c
[armeabi] Compile thumb  : redsocks <= socks4.c
[armeabi] Compile thumb  : redsocks <= socks5.c
[armeabi] Compile thumb  : redsocks <= http-relay.c
[armeabi] Compile thumb  : redsocks <= base.c
jni/../../base.c:28:20: fatal error: config.h: No such file or directory
 #include "config.h"

**Comment by SunPj** [comment]
yanggis, i've done with it. I got all configs from https://github.com/madeye/proxydroid

**Comment by yanggis** [comment]
@SunPj Thanks for your valuable tips.

**Pull request closed without merging**
